version: "3.9"
name: tp2
services:
  rabbitmq:
    build:
      context: ./containers/rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
  gateway_0:
    build:
      context: ./containers
      dockerfile: gateway/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/gateway.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=0
      - WEATHER_SIDE_TABLE_QUEUE_NAME=publish_weather
      - STATION_SIDE_TABLE_QUEUE_NAME=publish_station
    volumes:
      - .volumes/gateway_0:/volumes
  gateway_1:
    build:
      context: ./containers
      dockerfile: gateway/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/gateway.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=1
      - WEATHER_SIDE_TABLE_QUEUE_NAME=publish_weather
      - STATION_SIDE_TABLE_QUEUE_NAME=publish_station
    volumes:
      - .volumes/gateway_1:/volumes
  response_provider:
    container_name: response_provider
    build:
      context: ./containers
      dockerfile: response_provider/Dockerfile
    entrypoint: python3 /opt/app/response_provider.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - REPLICA_ID=0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - .volumes/response_provider:/volumes
  client0:
    build:
      context: ./containers
      dockerfile: client/Dockerfile
    entrypoint: python3 /opt/app/client.py
    depends_on:
      - gateway_0
      - gateway_1
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - DATA_FOLDER_PATH=/opt/app/.data
      - CLIENT_ID=original
      - CITIES=montreal,washington,toronto
    volumes:
      - ./.data_3/:/opt/app/.data/
  synchronizer:
    build:
      context: ./containers
      dockerfile: synchronizer/Dockerfile
    entrypoint: python3 /opt/app/synchronizer.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
    volumes:
      - .volumes/synchronizer:/volumes
  weather_aggregator_0:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - SIDE_TABLE_QUEUE_PREFIX=weather
      - SIDE_TABLE_ROUTING_KEY=publish_weather
      - REPLICA_ID=0
    volumes:
      - .volumes/weather_aggregator_0:/volumes
  weather_aggregator_1:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - SIDE_TABLE_QUEUE_PREFIX=weather
      - SIDE_TABLE_ROUTING_KEY=publish_weather
      - REPLICA_ID=1
    volumes:
      - .volumes/weather_aggregator_1:/volumes
  station_aggregator_0:
    build:
      context: ./containers
      dockerfile: station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - SIDE_TABLE_QUEUE_PREFIX=station
      - SIDE_TABLE_ROUTING_KEY=publish_station
      - REPLICA_ID=0
    volumes:
      - .volumes/station_aggregator_0:/volumes
  station_aggregator_1:
    build:
      context: ./containers
      dockerfile: station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - SIDE_TABLE_QUEUE_PREFIX=station
      - SIDE_TABLE_ROUTING_KEY=publish_station
      - REPLICA_ID=1
    volumes:
      - .volumes/station_aggregator_1:/volumes
  station_aggregator_2:
    build:
      context: ./containers
      dockerfile: station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - SIDE_TABLE_QUEUE_PREFIX=station
      - SIDE_TABLE_ROUTING_KEY=publish_station
      - REPLICA_ID=2
    volumes:
      - .volumes/station_aggregator_2:/volumes
  station_aggregator_3:
    build:
      context: ./containers
      dockerfile: station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - SIDE_TABLE_QUEUE_PREFIX=station
      - SIDE_TABLE_ROUTING_KEY=publish_station
      - REPLICA_ID=3
    volumes:
      - .volumes/station_aggregator_3:/volumes
  prec_filter_0:
    build:
      context: ./containers
      dockerfile: prec_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/prec_filter.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - PREC_LIMIT=30
      - REPLICA_ID=0
    volumes:
      - .volumes/prec_filter_0:/volumes
  prec_filter_1:
    build:
      context: ./containers
      dockerfile: prec_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/prec_filter.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - PREC_LIMIT=30
      - REPLICA_ID=1
    volumes:
      - .volumes/prec_filter_1:/volumes
  dur_avg_provider_0:
    build:
      context: ./containers
      dockerfile: dur_avg_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dur_avg_provider.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=0
    volumes:
      - .volumes/dur_avg_provider_0:/volumes
  distance_calculator_0:
    build:
      context: ./containers
      dockerfile: distance_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/distance_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=0
    volumes:
      - .volumes/distance_calculator_0:/volumes
  distance_calculator_1:
    build:
      context: ./containers
      dockerfile: distance_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/distance_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=1
    volumes:
      - .volumes/distance_calculator_1:/volumes
  dist_mean_calculator_0:
    build:
      context: ./containers
      dockerfile: dist_mean_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=0
    volumes:
      - .volumes/dist_mean_calculator_0:/volumes
  dist_mean_calculator_1:
    build:
      context: ./containers
      dockerfile: dist_mean_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=1
    volumes:
      - .volumes/dist_mean_calculator_1:/volumes
  dist_mean_provider_0:
    build:
      context: ./containers
      dockerfile: dist_mean_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_provider.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - MEAN_THRESHOLD=6.0
      - REPLICA_ID=0
    volumes:
      - .volumes/dist_mean_provider_0:/volumes
  year_filter_0:
    build:
      context: ./containers
      dockerfile: year_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/year_filter.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=0
    volumes:
      - .volumes/year_filter_0:/volumes
  year_filter_1:
    build:
      context: ./containers
      dockerfile: year_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/year_filter.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=1
    volumes:
      - .volumes/year_filter_1:/volumes
  trips_counter_0:
    build:
      context: ./containers
      dockerfile: trips_counter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trips_counter.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=0
    volumes:
      - .volumes/trips_counter_0:/volumes
  trips_counter_1:
    build:
      context: ./containers
      dockerfile: trips_counter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trips_counter.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=1
    volumes:
      - .volumes/trips_counter_1:/volumes
  trip_count_provider_0:
    build:
      context: ./containers
      dockerfile: trip_count_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trip_count_provider.py
    environment:
      - PYTHONHASHSEED=0
      - PYTHONUNBUFFERED=1
      - MULT_THRESHOLD=2
      - REPLICA_ID=0
    volumes:
      - .volumes/trip_count_provider_0:/volumes
