version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./containers/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  gateway:
    container_name: gateway
    build:
      context: ./containers
      dockerfile: gateway/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/gateway.py
    environment:
      - PYTHONHASHSEED=0
      - WASHINGTON_OUTPUT_AMOUNT=2
      - TORONTO_OUTPUT_AMOUNT=2
      - MONTREAL_OUTPUT_AMOUNT=2


  response_provider:
    container_name: response_provider
    build:
      context: ./containers
      dockerfile: response_provider/Dockerfile
    entrypoint: python3 /opt/app/response_provider.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    build:
      context: ./containers
      dockerfile: client/Dockerfile
    entrypoint: python3 /opt/app/client.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_FOLDER_PATH=/opt/app/.data
      - PUSH_ADDR=tcp://gateway:5555
      - REQ_ADDR=tcp://response_provider:5555
      - CITIES_WITH_GEODATA=montreal
      - CITIES_WITHOUT_GEODATA=washington,toronto
    volumes:
      - ./.data_3/:/opt/app/.data/

  synchronizer:
    build:
      context: ./containers
      dockerfile: synchronizer/Dockerfile
    entrypoint: python3 /opt/app/synchronizer.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  wa_weather_aggregator_0:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=washington
      - INPUT_QUEUE_SUFFIX=gateway_in
      - OUTPUT_QUEUE_SUFFIX=gateway_out
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=0
      - SIDE_TABLE_QUEUE_SUFFIX=weather

  wa_weather_aggregator_1:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=washington
      - INPUT_QUEUE_SUFFIX=gateway_in
      - OUTPUT_QUEUE_SUFFIX=gateway_out
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=1
      - SIDE_TABLE_QUEUE_SUFFIX=weather

  tor_weather_aggregator_0:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=toronto
      - INPUT_QUEUE_SUFFIX=gateway_in
      - OUTPUT_QUEUE_SUFFIX=gateway_out
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=0
      - SIDE_TABLE_QUEUE_SUFFIX=weather

  tor_weather_aggregator_1:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=toronto
      - INPUT_QUEUE_SUFFIX=gateway_in
      - OUTPUT_QUEUE_SUFFIX=gateway_out
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=1
      - SIDE_TABLE_QUEUE_SUFFIX=weather

  mon_weather_aggregator_0:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=montreal
      - INPUT_QUEUE_SUFFIX=gateway_in
      - OUTPUT_QUEUE_SUFFIX=gateway_out
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=0
      - SIDE_TABLE_QUEUE_SUFFIX=weather

  mon_weather_aggregator_1:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=montreal
      - INPUT_QUEUE_SUFFIX=gateway_in
      - OUTPUT_QUEUE_SUFFIX=gateway_out
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=1
      - SIDE_TABLE_QUEUE_SUFFIX=weather

  wa_station_aggregator_0:
    build:
      context: ./containers
      dockerfile: simple_station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/simple_station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=washington
      - INPUT_QUEUE_SUFFIX=gateway_out
      - PREC_FILTER_IN_QUEUE_NAME=prec_filter_in
      - PREC_FILTER_AMOUNT=2
      - YEAR_FILTER_IN_QUEUE_NAME=year_filter_in
      - YEAR_FILTER_AMOUNT=2
      - REPLICA_ID=0
      - SIDE_TABLE_QUEUE_SUFFIX=station

  wa_station_aggregator_1:
    build:
      context: ./containers
      dockerfile: simple_station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/simple_station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=washington
      - INPUT_QUEUE_SUFFIX=gateway_out
      - PREC_FILTER_IN_QUEUE_NAME=prec_filter_in
      - PREC_FILTER_AMOUNT=2
      - YEAR_FILTER_IN_QUEUE_NAME=year_filter_in
      - YEAR_FILTER_AMOUNT=2
      - REPLICA_ID=1
      - SIDE_TABLE_QUEUE_SUFFIX=station

  tor_station_aggregator_0:
    build:
      context: ./containers
      dockerfile: simple_station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/simple_station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=toronto
      - INPUT_QUEUE_SUFFIX=gateway_out
      - PREC_FILTER_IN_QUEUE_NAME=prec_filter_in
      - PREC_FILTER_AMOUNT=2
      - YEAR_FILTER_IN_QUEUE_NAME=year_filter_in
      - YEAR_FILTER_AMOUNT=2
      - REPLICA_ID=0
      - SIDE_TABLE_QUEUE_SUFFIX=station

  tor_station_aggregator_1:
    build:
      context: ./containers
      dockerfile: simple_station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/simple_station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=toronto
      - INPUT_QUEUE_SUFFIX=gateway_out
      - PREC_FILTER_IN_QUEUE_NAME=prec_filter_in
      - PREC_FILTER_AMOUNT=2
      - YEAR_FILTER_IN_QUEUE_NAME=year_filter_in
      - YEAR_FILTER_AMOUNT=2
      - REPLICA_ID=1
      - SIDE_TABLE_QUEUE_SUFFIX=station

  mon_station_aggregator_0:
    build:
      context: ./containers
      dockerfile: full_station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/full_station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=montreal
      - INPUT_QUEUE_SUFFIX=gateway_out
      - PREC_FILTER_IN_QUEUE_NAME=prec_filter_in
      - PREC_FILTER_AMOUNT=2
      - YEAR_FILTER_IN_QUEUE_NAME=year_filter_in
      - YEAR_FILTER_AMOUNT=2
      - DISTANCE_CALC_IN_QUEUE_NAME=distance_calc_in
      - DISTANCE_CALC_AMOUNT=2
      - REPLICA_ID=0
      - SIDE_TABLE_QUEUE_SUFFIX=station

  mon_station_aggregator_1:
    build:
      context: ./containers
      dockerfile: full_station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/full_station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - CITY_NAME=montreal
      - INPUT_QUEUE_SUFFIX=gateway_out
      - PREC_FILTER_IN_QUEUE_NAME=prec_filter_in
      - PREC_FILTER_AMOUNT=2
      - YEAR_FILTER_IN_QUEUE_NAME=year_filter_in
      - YEAR_FILTER_AMOUNT=2
      - DISTANCE_CALC_IN_QUEUE_NAME=distance_calc_in
      - DISTANCE_CALC_AMOUNT=2
      - REPLICA_ID=1
      - SIDE_TABLE_QUEUE_SUFFIX=station

  prec_filter_0:
    build:
      context: ./containers
      dockerfile: prec_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/prec_filter.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=prec_filter_in
      - OUTPUT_QUEUE=prec_filtered
      - OUTPUT_AMOUNT=2
      - PREC_LIMIT=30
      - REPLICA_ID=0

  prec_filter_1:
    build:
      context: ./containers
      dockerfile: prec_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/prec_filter.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=prec_filter_in
      - OUTPUT_QUEUE=prec_filtered
      - OUTPUT_AMOUNT=2
      - PREC_LIMIT=30
      - REPLICA_ID=1

  dur_avg_provider_0:
    build:
      context: ./containers
      dockerfile: dur_avg_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dur_avg_provider.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=prec_filtered
      - OUTPUT_QUEUE=avg_provider
      - REPLICA_ID=0

  dur_avg_provider_1:
    build:
      context: ./containers
      dockerfile: dur_avg_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dur_avg_provider.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=prec_filtered
      - OUTPUT_QUEUE=avg_provider
      - REPLICA_ID=1

  distance_calculator_0:
    build:
      context: ./containers
      dockerfile: distance_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/distance_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=distance_calc_in
      - OUTPUT_QUEUE=distance
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=0

  distance_calculator_1:
    build:
      context: ./containers
      dockerfile: distance_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/distance_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=distance_calc_in
      - OUTPUT_QUEUE=distance
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=1

  dist_mean_calculator_0:
    build:
      context: ./containers
      dockerfile: dist_mean_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=distance
      - OUTPUT_QUEUE=distance_mean
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=0

  dist_mean_calculator_1:
    build:
      context: ./containers
      dockerfile: dist_mean_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=distance
      - OUTPUT_QUEUE=distance_mean
      - OUTPUT_AMOUNT=1
      - REPLICA_ID=1

  dist_mean_provider_0:
    build:
      context: ./containers
      dockerfile: dist_mean_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_provider.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=distance_mean
      - OUTPUT_QUEUE=dist_mean_provider
      - REPLICA_ID=0
      - MEAN_THRESHOLD=6.0

  year_filter_0:
    build:
      context: ./containers
      dockerfile: year_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/year_filter.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=year_filter_in
      - OUTPUT_QUEUE=year_filtered
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=0

  year_filter_1:
    build:
      context: ./containers
      dockerfile: year_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/year_filter.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=year_filter_in
      - OUTPUT_QUEUE=year_filtered
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=1

  trips_counter_0:
    build:
      context: ./containers
      dockerfile: trips_counter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trips_counter.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=year_filtered
      - OUTPUT_QUEUE=trips_counted
      - OUTPUT_AMOUNT=2
      - REPLICA_ID=0

  trips_counter_1:
    build:
      context: ./containers
      dockerfile: trips_counter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trips_counter.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=year_filtered
      - OUTPUT_QUEUE=trips_counted
      - OUTPUT_AMOUNT=1
      - REPLICA_ID=1

  trip_count_provider_0:
    build:
      context: ./containers
      dockerfile: trip_count_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trip_count_provider.py
    environment:
      - PYTHONHASHSEED=0
      - INPUT_QUEUE=trips_counted
      - OUTPUT_QUEUE=trip_count_provider
      - REPLICA_ID=0
      - MULT_THRESHOLD=2