version: '3.9'
name: tp2
services:
  rabbitmq:
    build:
      context: ./containers/rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
  gateway:
    container_name: gateway
    build:
      context: ./containers
      dockerfile: gateway/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      weather_aggregator_0:
        condition: service_started
      weather_aggregator_1:
        condition: service_started
      station_aggregator_0:
        condition: service_started
      station_aggregator_1:
        condition: service_started
    entrypoint: python3 /opt/app/gateway.py
    environment:
      - PYTHONHASHSEED=0
  response_provider:
    container_name: response_provider
    build:
      context: ./containers
      dockerfile: response_provider/Dockerfile
    entrypoint: python3 /opt/app/response_provider.py
    depends_on:
      rabbitmq:
        condition: service_healthy
  client:
    build:
      context: ./containers
      dockerfile: client/Dockerfile
    entrypoint: python3 /opt/app/client.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_FOLDER_PATH=/opt/app/.data
      - PUSH_ADDR=tcp://gateway:5555
      - REQ_ADDR=tcp://response_provider:5555
      - CITIES=montreal,washington,toronto
    volumes:
      - ./.data_3/:/opt/app/.data/
  synchronizer:
    build:
      context: ./containers
      dockerfile: synchronizer/Dockerfile
    entrypoint: python3 /opt/app/synchronizer.py
    depends_on:
      rabbitmq:
        condition: service_healthy
  weather_aggregator_0:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - SIDE_TABLE_QUEUE_NAME=weather
      - REPLICA_ID=0
    volumes:
      - .volumes/weather_aggregator_0:/volumes
  weather_aggregator_1:
    build:
      context: ./containers
      dockerfile: weather_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/weather_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - SIDE_TABLE_QUEUE_NAME=weather
      - REPLICA_ID=1
    volumes:
      - .volumes/weather_aggregator_1:/volumes
  station_aggregator_0:
    build:
      context: ./containers
      dockerfile: station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - SIDE_TABLE_QUEUE_NAME=station
      - REPLICA_ID=0
    volumes:
      - .volumes/station_aggregator_0:/volumes
  station_aggregator_1:
    build:
      context: ./containers
      dockerfile: station_aggregator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/station_aggregator.py
    environment:
      - PYTHONHASHSEED=0
      - SIDE_TABLE_QUEUE_NAME=station
      - REPLICA_ID=1
    volumes:
      - .volumes/station_aggregator_1:/volumes
  prec_filter_0:
    build:
      context: ./containers
      dockerfile: prec_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/prec_filter.py
    environment:
      - PYTHONHASHSEED=0
      - PREC_LIMIT=30
      - REPLICA_ID=0
  prec_filter_1:
    build:
      context: ./containers
      dockerfile: prec_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/prec_filter.py
    environment:
      - PYTHONHASHSEED=0
      - PREC_LIMIT=30
      - REPLICA_ID=1
  dur_avg_provider_0:
    build:
      context: ./containers
      dockerfile: dur_avg_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dur_avg_provider.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=0
    volumes:
      - .volumes/dur_avg_provider_0:/volumes
  distance_calculator_0:
    build:
      context: ./containers
      dockerfile: distance_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/distance_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=0
  distance_calculator_1:
    build:
      context: ./containers
      dockerfile: distance_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/distance_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=1
  dist_mean_calculator_0:
    build:
      context: ./containers
      dockerfile: dist_mean_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=0
    volumes:
      - .volumes/dist_mean_calculator_0:/volumes
  dist_mean_calculator_1:
    build:
      context: ./containers
      dockerfile: dist_mean_calculator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_calculator.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=1
    volumes:
      - .volumes/dist_mean_calculator_1:/volumes
  dist_mean_provider_0:
    build:
      context: ./containers
      dockerfile: dist_mean_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/dist_mean_provider.py
    environment:
      - PYTHONHASHSEED=0
      - MEAN_THRESHOLD=6.0
      - REPLICA_ID=0
  year_filter_0:
    build:
      context: ./containers
      dockerfile: year_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/year_filter.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=0
  year_filter_1:
    build:
      context: ./containers
      dockerfile: year_filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/year_filter.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=1
  trips_counter_0:
    build:
      context: ./containers
      dockerfile: trips_counter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trips_counter.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=0
    volumes:
      - .volumes/trips_counter_0:/volumes
  trips_counter_1:
    build:
      context: ./containers
      dockerfile: trips_counter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trips_counter.py
    environment:
      - PYTHONHASHSEED=0
      - REPLICA_ID=1
    volumes:
      - .volumes/trips_counter_1:/volumes
  trip_count_provider_0:
    build:
      context: ./containers
      dockerfile: trip_count_provider/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: python3 /opt/app/trip_count_provider.py
    environment:
      - PYTHONHASHSEED=0
      - MULT_THRESHOLD=2
      - REPLICA_ID=0
